version: '3.7'

services:
  server-prod:
    container_name: server-prod
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=production